
site_name: 波场文档
nav:
    - 简介: 
        - 项目仓库: introduction/index.md
        - 波场共识: introduction/dpos.md
    - 接口:
        - Http接口: api/http.md
        - Rpc接口: api/rpc.md
    - 机制与算法:
        - 超级代表与委员会: mechanism&algorithm/sr.md
        - TRC-10: mechanism&algorithm/trc10.md  
        - 账户模型: mechanism&algorithm/account.md
        - 资源模型: mechanism&algorithm/resource.md
        - 去中心化交易所: mechanism&algorithm/dex.md
        - 多重签名: mechanism&algorithm/multi-signatures.md
        - 匿名交易: mechanism&algorithm/shielded-transaction.md
        - 系统合约: mechanism&algorithm/systemContracts.md   
    - 架构:
        - 网络: architecture/network.md
        - 数据库: architecture/database.md
        - 插件: architecture/plugin.md  
    - 智能合约: 
        - 虚拟机: contracts/tvm.md
        - 编译器: contracts/compiler.md    
        - 合约: contracts/contract.md  
        - TRC-20: contracts/trc20.md  
    - 开发者:
        - 官方节点: developers/official-public-nodes.md
        - 部署: developers/deployment.md
        - 资源: developers/resources.md
        - 参与开发: developers/contribution.md
        - 激励政策: developers/incentives.md
    - 客户端:  
        - 命令行钱包: clients/wallet-cli.md  
    - 常见问题: q&a/qa.md  
    - 术语: glossary.md  

theme: readthedocs
